# -*- coding: utf-8 -*-

deck_devoir = {"name":"devoir",
             "template":"deck.html", 
             "title":u"Devoir (to must)",
             "questions":[["Je %s te voir","dois"], 
                          ["Tu %s te voir","dois"], 
                          ["Il %s te voir","doit"], 
                          ["Elle %s te voir","doit"], 
                          ["Nous %s te voir","devons"], 
                          ["Vous %s te voir","devez"], 
                          ["Ils %s te voir","doivent"], 
                          ["Elles %s te voir","doivent"]], 
             "qparser": lambda ptrn, dctn : ptrn % u"<question2>⟨ ? ⟩</question2>", 
             "aparser": lambda ptrn, dctn : ptrn % ("<answer>%s</answer>" % dctn)}

deck_pouvoir = {"name":"pouvoir",
             "template":"deck.html", 
             "title":u"Pouvoir (to can)",
             "questions":[["Je %s te voir","peux"], 
                          ["Tu %s te voir","peux"], 
                          ["Il %s te voir","peut"], 
                          ["Elle %s te voir","peut"], 
                          ["Nous %s te voir","pouvons"], 
                          ["Vous %s te voir","pouvez"], 
                          ["Ils %s te voir","pouvent"], 
                          ["Elles %s te voir","pouvent"]], 
             "qparser": lambda ptrn, dctn : ptrn % u"<question2>⟨ ? ⟩</question2>", 
             "aparser": lambda ptrn, dctn : ptrn % ("<answer>%s</answer>" % dctn)}

deck_vouloir = {"name":"vouloir",
             "template":"deck.html", 
             "title":u"Vouloir (to want)",
             "questions":[["Je %s te voir","veux"], 
                          ["Tu %s te voir","veux"], 
                          ["Il %s te voir","veut"], 
                          ["Elle %s te voir","veut"], 
                          ["Nous %s te voir","voulons"], 
                          ["Vous %s te voir","voulez"], 
                          ["Ils %s te voir","veulent"], 
                          ["Elles %s te voir","veulent"]], 
             "qparser": lambda ptrn, dctn : ptrn % u"<question2>⟨ ? ⟩</question2>", 
             "aparser": lambda ptrn, dctn : ptrn % ("<answer>%s</answer>" % dctn)}

deck_faire = {"name":"faire",
             "template":"deck.html", 
             "title":u"faire (to do)",
             "questions":[["Je %s du sport","fais"], 
                          ["Tu %s du sport","fais"], 
                          ["Il %s du sport","fait"], 
                          ["Elle %s du sport","fait"], 
                          ["Nous %s du sport","faisons"], 
                          ["Vous %s du sport","faites"], 
                          ["Ils %s du sport","font"], 
                          ["Elles %s du sport","font"]], 
             "qparser": lambda ptrn, dctn : ptrn % u"<question2>⟨ ? ⟩</question2>", 
             "aparser": lambda ptrn, dctn : ptrn % ("<answer>%s</answer>" % dctn)}

deck_aller = {"name":"aller",
             "template":"deck.html", 
             "title":u"Aller (to go)",
             "questions":[[u"Je %s à l'école","vais"], 
                          [u"Tu %s à l'école","vas"], 
                          [u"Il %s à l'école","va"], 
                          [u"Elle %s à l'école","va"], 
                          [u"Nous %s à l'école","allons"], 
                          [u"Vous %s à l'école","allez"], 
                          [u"Ils %s à l'école","vont"], 
                          [u"Elles %s à l'école","vont"]], 
             "qparser": lambda ptrn, dctn : ptrn % u"<question2>⟨ ? ⟩</question2>", 
             "aparser": lambda ptrn, dctn : ptrn % ("<answer>%s</answer>" % dctn)}

deck_avoir = {"name":"avoir",
             "template":"deck.html", 
             "title":u"avoir",
             "questions":[["Je %s une pomme","'ai"], 
                          ["Tu %s une pomme","as"], 
                          ["Il %s une pomme","a"], 
                          ["Elle %s une pomme","a"], 
                          ["Nous %s une pomme","avons"], 
                          ["Vous %s une pomme","avez"], 
                          ["Ils %s une pomme","ont"], 
                          ["Elles %s une pomme","ont"]], 
             "qparser": lambda ptrn, dctn : ptrn % u"<question2>⟨ ? ⟩</question2>", 
             "aparser": lambda ptrn, dctn : ptrn % ("<answer>%s</answer>" % dctn)}

deck_etre = {"name":"etre", 
             "template":"deck.html", 
             "title":u"être",
             "questions":[["Je %s grande","suis"], 
                          ["Tu %s grande","es"], 
                          ["Il %s grande","est"], 
                          ["Elle %s grande","est"], 
                          ["Nous %s grandes","sommes"], 
                          ["Vous %s grandes",u"êtes"], 
                          ["Ils %s grandes","sont"], 
                          ["Elles %s grandes","sont"]], 
             "qparser": lambda ptrn, dctn : ptrn % u"<question2>⟨ ? ⟩</question2>", 
             "aparser": lambda ptrn, dctn : ptrn % ("<answer>%s</answer>" % dctn)}

deck_Ver = {"name":"Ver", 
             "template":"deck.html", 
             "title":u"V-er",
             "questions":[["Je %s une pomme","mang<frm>e</frm>"], 
                          ["Tu %s une pomme","mang<frm>es</frm>"], 
                          ["Il %s une pomme","mang<frm>e</frm>"], 
                          ["Elle %s une pomme","mang<frm>e</frm>"], 
                          ["Nous %s une pomme","mang<frm>ons</frm>"], 
                          ["Vous %s une pomme","mang<frm>ez</frm>"], 
                          ["Ils %s une pomme","mang<frm>ent</frm>"], 
                          ["Elles %s une pomme","mang<frm>ent</frm>"]], 
             "qparser": lambda ptrn, dctn : ptrn % u"<question2>⟨ mang<frm>er</frm> ⟩</question2>", 
             "aparser": lambda ptrn, dctn : ptrn % ("<answer>%s</answer>" % dctn)}

deck_Vir = {"name":"Vir", 
             "template":"deck.html", 
             "title":u"V-ir",
             "questions":[["Je %s de livre","fin<frm>is</frm>"], 
                          ["Tu %s de livre","fin<frm>is</frm>"], 
                          ["Il %s de livre","fin<frm>it</frm>"], 
                          ["Elle %s de livre","fin<frm>it</frm>"], 
                          ["Nous %s des livres","fin<frm>issons</frm>"], 
                          ["Vous %s de livre","fin<frm>issez</frm>"], 
                          ["Ils %s des livres","fin<frm>issent</frm>"], 
                          ["Elles %s des lires","fin<frm>issent</frm>"]], 
             "qparser": lambda ptrn, dctn : ptrn % u"<question2>⟨ fin<frm>ir</frm> ⟩</question2>", 
             "aparser": lambda ptrn, dctn : ptrn % ("<answer>%s</answer>" % dctn)}
